### ISSUE TITLE
Error loading ./tf_operation.so at Step 1

### ISSUE THREAD

**Issue by asunyz** [learning1234embed/NeuralWeightVirtualization#2]
HI, I get the following error while running "python weight_virtualization.py -mode=a -network_path=gsc"

gsc/gsc_network_fisher.npy
[match_page_by_cost]
Traceback (most recent call last):
  File "weight_virtualization.py", line 1303, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "weight_virtualization.py", line 1148, in main
    wv.add_vnn(args.network_path)
  File "weight_virtualization.py", line 124, in add_vnn
    self.match_weight_page(vnn)
  File "weight_virtualization.py", line 826, in match_weight_page
    self.match_page_by_cost(vnn)
  File "weight_virtualization.py", line 661, in match_page_by_cost
    weight_virtualization_op = tf.load_op_library(self.weight_virtualization_op_filename)
  File "/media/myst/anaconda3/envs/python2.7/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./tf_operation.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

I am using tensorflow version 1.13.1

**Comment by asunyz** [comment]
Ok. I changed tensorflow installation from conda to pip and fixed this issue. Should be a Anaconda problem.
